imports:
  - { resource: services/classes.yaml }
  - { resource: services/services.yaml }
  - { resource: services/controllers.yaml }
  - { resource: services/adminApi.yaml }
  - { resource: services/commandApi.yaml }
  - { resource: services/graphQLApi.yaml }
  - { resource: services/restApi.yaml }

services:
  # Better manage of symfony exceptions, display errors with better graphic (prod) and different ways, example jsons
  lturi.http_exception:
    alias: Lturi\SymfonyExtensions\Framework\Service\HttpExceptionService
    public: true
  Lturi\SymfonyExtensions\Framework\Service\HttpExceptionService:
    public: true
    autowire: true
    arguments:
      - '@router.default'
      - '@service_container'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  Lturi\SymfonyExtensions\Framework\EntityUtility\EntityDataValidator:
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@Lturi\SymfonyExtensions\Framework\EntityUtility\EntitiesDescriptor'
      - '@Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface'

  Lturi\SymfonyExtensions\Framework\EntityUtility\EntityManagerInterface:
    public: true
    class: Lturi\SymfonyExtensions\Framework\EntityUtility\EntityManagerDoctrine
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
      - '@Symfony\Component\Validator\Validator\ValidatorInterface'
      - '@Lturi\SymfonyExtensions\Framework\EntityUtility\EntityDataValidator'

  # Voters
  Lturi\SymfonyExtensions\Framework\EntityUtility\Voter\SuperAdminVoter:
    public: true
    arguments:
      - !tagged_iterator security.voter
      - 'access_decision_manager.strategy'
    tags:
      - { name: security.voter }