imports:
  - { resource: services/classes.yaml }
  - { resource: services/services.yaml }
  - { resource: services/controllers.yaml }
  - { resource: services/commandApi.yaml }

services:
  # Better manage of symfony exceptions, display errors with better graphic (prod) and different ways, example jsons
  lturi.http_exception:
    alias: Lturi\SymfonyExtensions\Framework\Service\HttpExceptionService
    public: true
  Lturi\SymfonyExtensions\Framework\Service\HttpExceptionService:
    public: true
    autowire: true
    arguments:
      - '@router.default'
      - '@service_container'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
