services:

  # Response services injected in routes params to display a formatted response
  lturi.api_response:
    alias: Lturi\SymfonyExtensions\Services\Response\ApiResponse
    public: true
  Lturi\SymfonyExtensions\Services\Response\ApiResponse:
    public: true
    autowire: true
    arguments: ~

  # Cached responses types -> extensions for ApiResponse
  lturi.cacheable_api_response:
    alias: Lturi\SymfonyExtensions\Services\Response\CacheableApiResponse
    public: true
  Lturi\SymfonyExtensions\Services\Response\CacheableApiResponse:
    public: true
    autowire: true
    arguments: ~
  lturi.cacheable_response:
    alias: Lturi\SymfonyExtensions\Services\Response\CacheableResponse
    public: true
  Lturi\SymfonyExtensions\Services\Response\CacheableResponse:
    public: true
    autowire: true
    arguments: ~

  # Entities descriptor (entity, properties etc)
  Lturi\SymfonyExtensions\Classes\Entities\EntitiesDescriptor:
    arguments: ["@Symfony\\Contracts\\Cache\\CacheInterface"]
    tags:
      - { name: controller.service_arguments }