services:
  # Routes loader
  lturi.route_loader:
    alias: Lturi\SymfonyExtensions\Framework\Service\RouteLoader
    public: true
  Lturi\SymfonyExtensions\Framework\Service\RouteLoader:
    public: true
    autowire: true
    arguments: ["@service_container"]
    tags:
      - { name: routing.loader }

  # Controllers registering
  Lturi\SymfonyExtensions\Framework\Controller\RoutesController:
    tags:
      - { name: controller.service_arguments }
  Lturi\SymfonyExtensions\Framework\Controller\TranslationController:
    tags:
      - { name: controller.service_arguments }
  Lturi\SymfonyExtensions\Framework\Controller\EntitiesController:
    arguments: ["@service_container", "@Lturi\\SymfonyExtensions\\Framework\\EntityUtility\\EntitiesDescriptor"]
    tags:
      - { name: controller.service_arguments }
  Lturi\SymfonyExtensions\JsonApi\Controller\JsonapiController:
    public: true
    autowire: true
    arguments:
      - "@service_container"
      - "@Lturi\\SymfonyExtensions\\Framework\\EntityUtility\\EntitiesDescriptor"
      - "@Lturi\\SymfonyExtensions\\JsonApi\\Entity\\RouteDescriptor"
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: controller.service_arguments }


  Lturi\SymfonyExtensions\JsonApi\Controller\InfoController:
    arguments:
      - "@service_container"
      - "@Lturi\\SymfonyExtensions\\Framework\\EntityUtility\\EntitiesDescriptor"
    tags:
      - { name: controller.service_arguments }