services:
  # Routes loader
  lturi.route_loader:
    alias: Lturi\SymfonyExtensions\Framework\Service\RouteLoader
    public: true
  Lturi\SymfonyExtensions\Framework\Service\RouteLoader:
    public: true
    autowire: true
    arguments: ["@service_container"]
    tags:
      - { name: routing.loader }

  # Controllers registering
  Lturi\SymfonyExtensions\Framework\Controller\RoutesController:
    tags:
      - { name: controller.service_arguments }
  Lturi\SymfonyExtensions\Framework\Controller\TranslationController:
    tags:
      - { name: controller.service_arguments }
  Lturi\SymfonyExtensions\Framework\Controller\EntitiesController:
    arguments: ["@service_container", "@Lturi\\SymfonyExtensions\\JsonApi\\Entity\\EntitiesDescriptor"]
    tags:
      - { name: controller.service_arguments }
  Lturi\SymfonyExtensions\JsonApi\Controller\JsonapiController:
    arguments: ["@service_container", "@Lturi\\SymfonyExtensions\\JsonApi\\Entity\\EntitiesDescriptor", "@doctrine.orm.entity_manager"]
    tags:
      - { name: controller.service_arguments }