services:
  Lturi\SymfonyExtensions\GraphQLApi\Controller\GraphQLController:
    public: true
    autowire: true
    arguments:
      - '%commandApiEntities%'
      - '@Lturi\SymfonyExtensions\Framework\EntityUtility\EntitiesDescriptor'
      - '@Lturi\SymfonyExtensions\Framework\EntityUtility\EntityManagerInterface'
      - '@Lturi\SymfonyExtensions\Framework\EntityUtility\EntityDataValidator'
      - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
      - '%env(resolve:APP_ENV)%'
    tags:
      - { name: controller.service_arguments }

  Lturi\SymfonyExtensions\GraphQLApi\Entity\RouteDescriptor:
    public: true
    autowire: true